<div style="border:solid green 2px; padding: 20px">
Мария, привет и хорошего дня! <br>
Меня зовут Сергей Дроздов, и я буду проверять твой проект. Предлагаю общаться на «ты». Если тебе удобнее общаться на "Вы", просто дай знать. 

Ты уже проделал большую работу над проектом, но давай сделаем его еще лучше. Ниже ты найдешь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать цветовую разметку:

<div class="alert alert-danger">
<b>Комментарий ревьюера: &#10060; </b> Так будут выделены комментарии с указаниями, обязательными к выполнению. Без их выполнения проект не будет принят. </div>

<div class="alert alert-warning">
<b>Комментарий ревьюера:
&#9888;</b> Так будут выделены некритичные замечания. Их отработка позволит улучшить качество твоего проекта.
</div>

<div class="alert alert-success">
<b>Комментарий ревьюера:
&#9989;</b> Так будут выделены остальные комментарии, полезные лайфхаки и ссылки на сторонние ресурсы </div>
    <br>
    
<div style="border-radius: 15px; border: 3px solid indigo; padding: 15px;background:rgb(185, 176, 207)">
<b>Итоговый комментарий ревьюера:
</b> Так будут выделены итоговые комментарии.
</div>

Для наиболее эффективной и оперативной работы над проектом, мне хотелось бы иметь обратную связь. Не стесняйся задавать вопросы. Если ты что-либо меняешь в проекте, пожалуйста, комментируй это. Мне будет легче отследить изменения, если ты выделишь свои комментарии:
<div class="alert alert-info"> <b>Комментарий студента:</b> Например так</div>

# Прогнозирование длительности использования пользователем услуг связи и интернета

Оператор связи «Ниединогоразрыва.ком» хочет научиться прогнозировать отток клиентов. Если выяснится, что пользователь планирует уйти, ему будут предложены промокоды и специальные условия. Команда оператора собрала персональные данные о некоторых клиентах, информацию об их тарифах и договорах.

Соответственно, задачей данного проекта является создание модели, которая учитывая персональные данные пользователя и подключенные тарифы смогла бы предсказать уровень его лояльности.

<div class="alert alert-success">
<b>Комментарий ревьюера:
&#9989;</b> Хорошо! Название и описание на месте!</div>
    <br>

# Загрузка данных и их предобработка

In [1]:
import pandas as pd

In [2]:
contract_df = pd.read_csv('/datasets/final_provider/contract.csv')
personal_df = pd.read_csv('/datasets/final_provider/personal.csv')
internet_df = pd.read_csv('/datasets/final_provider/internet.csv')
phone_df = pd.read_csv('/datasets/final_provider/phone.csv')

In [3]:
contract_df.head()

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,2020-01-01,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,2017-04-01,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,2016-05-01,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,2019-09-01,2019-11-01 00:00:00,Month-to-month,Yes,Electronic check,70.70,151.65

In [4]:
contract_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   object
 2   EndDate           7043 non-null   object
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object
dtypes: float64(1), object(7)
memory usage: 440.3+ KB

In [5]:
contract_df.loc[contract_df['TotalCharges'] == ' ', 'TotalCharges'] = contract_df.loc[contract_df['TotalCharges'] == ' ', 'MonthlyCharges']

In [6]:
contract_df['TotalCharges'] = contract_df['TotalCharges'].astype('float')

In [7]:
contract_df['BeginDate'] = pd.to_datetime(
    contract_df['BeginDate'], format='%Y-%m-%d'
)

In [8]:
contract_df.loc[contract_df['EndDate'] == 'No', 'EndDate'] = '2020-04-30 00:00:00'

In [9]:
contract_df['EndDate'] = pd.to_datetime(
    contract_df['EndDate'], format='%Y-%m-%d %H:%M:%S'
)

In [10]:
contract_df.isna().sum()

customerID          0
BeginDate           0
EndDate             0
Type                0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [11]:
contract_df.duplicated().sum()

0

In [12]:
contract_df['duration'] = contract_df['EndDate'] - contract_df['BeginDate']

In [13]:
contract_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   datetime64[ns]
 2   EndDate           7043 non-null   datetime64[ns]
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   float64
 8   duration          7043 non-null   timedelta64[ns]
dtypes: datetime64[ns](2), float64(2), object(4), timedelta64[ns](1)
memory usage: 495.3+ KB

In [14]:
contract_df.head()

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,duration
0,7590-VHVEG,2020-01-01,2020-04-30,Month-to-month,Yes,Electronic check,29.85,29.85,120 days
1,5575-GNVDE,2017-04-01,2020-04-30,One year,No,Mailed check,56.95,1889.50,1125 days
2,3668-QPYBK,2019-10-01,2019-12-01,Month-to-month,Yes,Mailed check,53.85,108.15,61 days
3,7795-CFOCW,2016-05-01,2020-04-30,One year,No,Bank transfer (automatic),42.30,1840.75,1460 days
4,9237-HQITU,2019-09-01,2019-11-01,Month-to-month,Yes,Electronic check,70.70,151.65,61 days

In [15]:
personal_df.head()

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [16]:
personal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

In [17]:
personal_df.isna().sum()

customerID       0
gender           0
SeniorCitizen    0
Partner          0
Dependents       0
dtype: int64

In [18]:
personal_df.duplicated().sum()

0

In [19]:
internet_df.head()

,customerID,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Fiber optic,No,No,No,No,No,No

In [20]:
internet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5517 non-null   object
 1   InternetService   5517 non-null   object
 2   OnlineSecurity    5517 non-null   object
 3   OnlineBackup      5517 non-null   object
 4   DeviceProtection  5517 non-null   object
 5   TechSupport       5517 non-null   object
 6   StreamingTV       5517 non-null   object
 7   StreamingMovies   5517 non-null   object
dtypes: object(8)
memory usage: 344.9+ KB

In [21]:
internet_df.isna().sum()

customerID          0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
dtype: int64

In [22]:
internet_df.duplicated().sum()

0

In [23]:
phone_df.head()

   customerID MultipleLines
0  5575-GNVDE            No
1  3668-QPYBK            No
2  9237-HQITU            No
3  9305-CDSKC           Yes
4  1452-KIOVK           Yes

In [24]:
phone_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6361 entries, 0 to 6360
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     6361 non-null   object
 1   MultipleLines  6361 non-null   object
dtypes: object(2)
memory usage: 99.5+ KB

In [25]:
phone_df.isna().sum()

customerID       0
MultipleLines    0
dtype: int64

In [26]:
phone_df.duplicated().sum()

0

Предварительные выводы

Датасеты довольно качественные, в них нет явных пропусков и дубликатов.

В процессе обработки contract_df были изменены типы данных: TotalCharges на float, BeginDate и EndDate на datetime.

Был создан столбец duration, в котором указана длительность использования пользователями услуг оператора.

<div class="alert alert-success">
<b>Комментарий ревьюера:
&#9989;</b> Хорошо! </div>
    <br>

Уточняющие вопросы

- Правильно ли обозначить столбец duration как таргет и тогда решать задачу регрессии?

<div class="alert alert-success">
<b>Комментарий ревьюера:
&#9989;</b> Нет, таргет у нас - ушел клиент или нет(end_date) </div>
    <br>

# План работы

- объединить датасеты по столбцу customerID, так чтобы не произошло утечки данных.
- заполнить образовавшиеся пропуски выбранными значениями, там где их мало, удалить.
- провести исследовательский анализ данных и визуализировать нужные закономерности в данных.
- провести аналих признаков на мультиколлинеарность: посторить матрицу корреляции для количественных признаков и использовать Cramer's V для категориальных.
- провести проверку на дисбаланс классов.

- разбить выборку на обучающую и тестовую.
- провести кодировку и масштабирование признаков.
- обучить 2 модели, одна из них бустинговая.
- подобрать гиперпараметры с помощью GridSearchCV.
- выбрать итоговую модель по результатам кросс-валидации.
- проверить качество итоговой модели на тестовой выборке с помощью метрики ROC-AUC.
- построить ROC-кривую.
- построить матрицу ошибок.

- подвести итоги.

<div class="alert alert-success">
<b>Комментарий ревьюера:
&#9989;</b> Хороший план! </div>
    <br>

<div style="border-radius: 15px; border: 3px solid indigo; padding: 15px;background:rgb(185, 176, 207)">
<b>Итоговый комментарий ревьюера:
</b> Молодец! Можешь приступать ко второй части работы!
</div>